import { MysteryItem } from './types';

export const WHO_ITEMS: MysteryItem[] = [
  { id: 'carpenter', da: 'Snedker', en: 'Carpenter', de: 'Schreiner', imageSeed: 'person,carpenter' },
  { id: 'judge', da: 'Dommer', en: 'Judge', de: 'Richter', imageSeed: 'person,judge' },
  { id: 'policeman', da: 'Politimand', en: 'Policeman', de: 'Polizist', imageSeed: 'person,police' },
  { id: 'clown', da: 'Klovn', en: 'Clown', de: 'Clown', imageSeed: 'person,clown' },
  { id: 'doctor', da: 'Læge', en: 'Doctor', de: 'Arzt', imageSeed: 'person,doctor' },
  { id: 'chef', da: 'Kok', en: 'Chef', de: 'Koch', imageSeed: 'person,chef' },
  { id: 'astronaut', da: 'Astronaut', en: 'Astronaut', de: 'Astronaut', imageSeed: 'person,astronaut' },
  { id: 'pirate', da: 'Pirat', en: 'Pirate', de: 'Pirat', imageSeed: 'person,pirate' },
  { id: 'ninja', da: 'Ninja', en: 'Ninja', de: 'Ninja', imageSeed: 'person,ninja' },
  { id: 'viking', da: 'Viking', en: 'Viking', de: 'Wikinger', imageSeed: 'person,viking' },
  { id: 'ballerina', da: 'Ballerina', en: 'Ballerina', de: 'Ballerina', imageSeed: 'person,ballerina' },
  { id: 'cowboy', da: 'Cowboy', en: 'Cowboy', de: 'Cowboy', imageSeed: 'person,cowboy' },
  { id: 'wizard', da: 'Troldmand', en: 'Wizard', de: 'Zauberer', imageSeed: 'person,wizard' },
  { id: 'waiter', da: 'Tjener', en: 'Waiter', de: 'Kellner', imageSeed: 'person,waiter' },
  { id: 'pilot', da: 'Pilot', en: 'Pilot', de: 'Pilot', imageSeed: 'person,pilot' },
  { id: 'knight', da: 'Ridder', en: 'Knight', de: 'Ritter', imageSeed: 'person,knight' },
  { id: 'queen', da: 'Dronning', en: 'Queen', de: 'Königin', imageSeed: 'person,queen' },
  { id: 'king', da: 'Konge', en: 'King', de: 'König', imageSeed: 'person,king' },
  { id: 'spy', da: 'Spion', en: 'Spy', de: 'Spion', imageSeed: 'person,spy' },
  { id: 'detective', da: 'Detektiv', en: 'Detective', de: 'Detektiv', imageSeed: 'person,detective' },
  { id: 'ghost', da: 'Spøgelse', en: 'Ghost', de: 'Geist', imageSeed: 'person,ghost' },
  { id: 'zombie', da: 'Zombie', en: 'Zombie', de: 'Zombie', imageSeed: 'person,zombie' },
  { id: 'alien', da: 'Rumvæsen', en: 'Alien', de: 'Außerirdischer', imageSeed: 'person,alien' },
  { id: 'robot', da: 'Robot', en: 'Robot', de: 'Roboter', imageSeed: 'person,robot' },
  { id: 'superhero', da: 'Superhelt', en: 'Superhero', de: 'Superheld', imageSeed: 'person,superhero' },
  { id: 'firefighter', da: 'Brandmand', en: 'Firefighter', de: 'Feuerwehrmann', imageSeed: 'person,firefighter' },
  { id: 'nurse', da: 'Sygeplejerske', en: 'Nurse', de: 'Krankenschwester', imageSeed: 'person,nurse' },
  { id: 'teacher', da: 'Lærer', en: 'Teacher', de: 'Lehrer', imageSeed: 'person,teacher' },
  { id: 'student', da: 'Elev', en: 'Student', de: 'Schüler', imageSeed: 'person,student' },
  { id: 'athlete', da: 'Atlet', en: 'Athlete', de: 'Athlet', imageSeed: 'person,athlete' },
  { id: 'diver', da: 'Dykker', en: 'Diver', de: 'Taucher', imageSeed: 'person,diver' },
  { id: 'explorer', da: 'Eventyrer', en: 'Explorer', de: 'Entdecker', imageSeed: 'person,explorer' },
  { id: 'magician', da: 'Tryllekunstner', en: 'Magician', de: 'Magier', imageSeed: 'person,magician' },
  { id: 'rockstar', da: 'Rockstjerne', en: 'Rockstar', de: 'Rockstar', imageSeed: 'person,rockstar' },
  { id: 'scientist', da: 'Forsker', en: 'Scientist', de: 'Wissenschaftler', imageSeed: 'person,scientist' },
  { id: 'mechanic', da: 'Mekaniker', en: 'Mechanic', de: 'Mechaniker', imageSeed: 'person,mechanic' },
  { id: 'gardener', da: 'Gartner', en: 'Gardener', de: 'Gärtner', imageSeed: 'person,gardener' },
  { id: 'postman', da: 'Postbud', en: 'Postman', de: 'Postbote', imageSeed: 'person,postman' },
  { id: 'librarian', da: 'Bibliotekar', en: 'Librarian', de: 'Bibliothekar', imageSeed: 'person,librarian' },
  { id: 'monk', da: 'Munk', en: 'Monk', de: 'Mönch', imageSeed: 'person,monk' },
  { id: 'nun', da: 'Nonne', en: 'Nun', de: 'Nonne', imageSeed: 'person,nun' },
  { id: 'pharaoh', da: 'Farao', en: 'Pharaoh', de: 'Pharao', imageSeed: 'person,pharaoh' },
  { id: 'samurai', da: 'Samurai', en: 'Samurai', de: 'Samurai', imageSeed: 'person,samurai' },
  { id: 'gladiator', da: 'Gladiator', en: 'Gladiator', de: 'Gladiator', imageSeed: 'person,gladiator' },
  { id: 'lifeguard', da: 'Livredder', en: 'Lifeguard', de: 'Rettungsschwimmer', imageSeed: 'person,lifeguard' },
  { id: 'baker', da: 'Bager', en: 'Baker', de: 'Bäcker', imageSeed: 'person,baker' },
  { id: 'butcher', da: 'Slagter', en: 'Butcher', de: 'Metzger', imageSeed: 'person,butcher' },
  { id: 'fisherman', da: 'Fisker', en: 'Fisherman', de: 'Fischer', imageSeed: 'person,fisherman' },
  { id: 'farmer', da: 'Landmand', en: 'Farmer', de: 'Bauer', imageSeed: 'person,farmer' },
  { id: 'artist', da: 'Kunstner', en: 'Artist', de: 'Künstler', imageSeed: 'person,artist' },
];

export const WHAT_ITEMS: MysteryItem[] = [
  { id: 'burger', da: 'Burger', en: 'Burger', de: 'Burger', imageSeed: 'object,burger' },
  { id: 'paper', da: 'Papir', en: 'Paper', de: 'Papier', imageSeed: 'object,paper' },
  { id: 'bell', da: 'Klokke', en: 'Bell', de: 'Glocke', imageSeed: 'object,bell' },
  { id: 'golf_club', da: 'Golfkølle', en: 'Golf Club', de: 'Golfschläger', imageSeed: 'object,golf' },
  { id: 'umbrella', da: 'Paraply', en: 'Umbrella', de: 'Regenschirm', imageSeed: 'object,umbrella' },
  { id: 'banana', da: 'Banan', en: 'Banana', de: 'Banane', imageSeed: 'object,banana' },
  { id: 'wrench', da: 'Svensknøgle', en: 'Wrench', de: 'Schraubenschlüssel', imageSeed: 'object,wrench' },
  { id: 'candle', da: 'Stearinlys', en: 'Candle', de: 'Kerze', imageSeed: 'object,candle' },
  { id: 'keyboard', da: 'Tastatur', en: 'Keyboard', de: 'Tastatur', imageSeed: 'object,keyboard' },
  { id: 'shoe', da: 'Sko', en: 'Shoe', de: 'Schuh', imageSeed: 'object,shoe' },
  { id: 'cactus', da: 'Kaktus', en: 'Cactus', de: 'Kaktus', imageSeed: 'object,cactus' },
  { id: 'rubber_duck', da: 'Badeand', en: 'Rubber Duck', de: 'Gummiente', imageSeed: 'object,duck' },
  { id: 'frying_pan', da: 'Stegepande', en: 'Frying Pan', de: 'Bratpfanne', imageSeed: 'object,pan' },
  { id: 'violin', da: 'Violin', en: 'Violin', de: 'Violine', imageSeed: 'object,violin' },
  { id: 'trophy', da: 'Pokal', en: 'Trophy', de: 'Pokal', imageSeed: 'object,trophy' },
  { id: 'telescope', da: 'Teleskop', en: 'Telescope', de: 'Teleskop', imageSeed: 'object,telescope' },
  { id: 'microscope', da: 'Mikroskop', en: 'Microscope', de: 'Mikroskop', imageSeed: 'object,microscope' },
  { id: 'compass', da: 'Kompas', en: 'Compass', de: 'Kompass', imageSeed: 'object,compass' },
  { id: 'map', da: 'Kort', en: 'Map', de: 'Karte', imageSeed: 'object,map' },
  { id: 'key', da: 'Nøgle', en: 'Key', de: 'Schlüssel', imageSeed: 'object,key' },
  { id: 'hammer', da: 'Hammer', en: 'Hammer', de: 'Hammer', imageSeed: 'object,hammer' },
  { id: 'saw', da: 'Sav', en: 'Saw', de: 'Säge', imageSeed: 'object,saw' },
  { id: 'scissors', da: 'Saks', en: 'Scissors', de: 'Schere', imageSeed: 'object,scissors' },
  { id: 'pencil', da: 'Blyant', en: 'Pencil', de: 'Bleistift', imageSeed: 'object,pencil' },
  { id: 'brush', da: 'Pensel', en: 'Brush', de: 'Pinsel', imageSeed: 'object,brush' },
  { id: 'camera', da: 'Kamera', en: 'Camera', de: 'Kamera', imageSeed: 'object,camera' },
  { id: 'phone', da: 'Telefon', en: 'Phone', de: 'Telefon', imageSeed: 'object,phone' },
  { id: 'laptop', da: 'Laptop', en: 'Laptop', de: 'Laptop', imageSeed: 'object,laptop' },
  { id: 'guitar', da: 'Guitar', en: 'Guitar', de: 'Gitarre', imageSeed: 'object,guitar' },
  { id: 'drum', da: 'Tromme', en: 'Drum', de: 'Trommel', imageSeed: 'object,drum' },
  { id: 'trumpet', da: 'Trompet', en: 'Trumpet', de: 'Trompete', imageSeed: 'object,trumpet' },
  { id: 'flute', da: 'Fløjte', en: 'Flute', de: 'Flöte', imageSeed: 'object,flute' },
  { id: 'ball', da: 'Bold', en: 'Ball', de: 'Ball', imageSeed: 'object,ball' },
  { id: 'bat', da: 'Bat', en: 'Bat', de: 'Schläger', imageSeed: 'object,bat' },
  { id: 'racket', da: 'Ketsjer', en: 'Racket', de: 'Schläger', imageSeed: 'object,racket' },
  { id: 'bicycle', da: 'Cykel', en: 'Bicycle', de: 'Fahrrad', imageSeed: 'object,bicycle' },
  { id: 'skateboard', da: 'Skateboard', en: 'Skateboard', de: 'Skateboard', imageSeed: 'object,skateboard' },
  { id: 'rollerblades', da: 'Rulleskøjter', en: 'Rollerblades', de: 'Inlineskates', imageSeed: 'object,rollerblades' },
  { id: 'helmet', da: 'Hjelm', en: 'Helmet', de: 'Helm', imageSeed: 'object,helmet' },
  { id: 'shield', da: 'Skjold', en: 'Shield', de: 'Schild', imageSeed: 'object,shield' },
  { id: 'sword', da: 'Sværd', en: 'Sword', de: 'Schwert', imageSeed: 'object,sword' },
  { id: 'bow', da: 'Bue', en: 'Bow', de: 'Bogen', imageSeed: 'object,bow' },
  { id: 'arrow', da: 'Pil', en: 'Arrow', de: 'Pfeil', imageSeed: 'object,arrow' },
  { id: 'book', da: 'Bog', en: 'Book', de: 'Buch', imageSeed: 'object,book' },
  { id: 'newspaper', da: 'Avis', en: 'Newspaper', de: 'Zeitung', imageSeed: 'object,newspaper' },
  { id: 'magazine', da: 'Magasin', en: 'Magazine', de: 'Magazin', imageSeed: 'object,magazine' },
  { id: 'letter', da: 'Brev', en: 'Letter', de: 'Brief', imageSeed: 'object,letter' },
  { id: 'box', da: 'Kasse', en: 'Box', de: 'Kiste', imageSeed: 'object,box' },
  { id: 'bag', da: 'Taske', en: 'Bag', de: 'Tasche', imageSeed: 'object,bag' },
  { id: 'wallet', da: 'Pung', en: 'Wallet', de: 'Brieftasche', imageSeed: 'object,wallet' },
];

export const WHERE_ITEMS: MysteryItem[] = [
  { id: 'garden', da: 'Have', en: 'Garden', de: 'Garten', imageSeed: 'place,garden' },
  { id: 'cemetery', da: 'Kirkegård', en: 'Cemetery', de: 'Friedhof', imageSeed: 'place,cemetery' },
  { id: 'basement', da: 'Kælder', en: 'Basement', de: 'Keller', imageSeed: 'place,basement' },
  { id: 'sweden', da: 'Sverige', en: 'Sweden', de: 'Schweden', imageSeed: 'place,sweden' },
  { id: 'library', da: 'Bibliotek', en: 'Library', de: 'Bibliothek', imageSeed: 'place,library' },
  { id: 'kitchen', da: 'Køkken', en: 'Kitchen', de: 'Küche', imageSeed: 'place,kitchen' },
  { id: 'forest', da: 'Skov', en: 'Forest', de: 'Wald', imageSeed: 'place,forest' },
  { id: 'beach', da: 'Strand', en: 'Beach', de: 'Strand', imageSeed: 'place,beach' },
  { id: 'cinema', da: 'Biograf', en: 'Cinema', de: 'Kino', imageSeed: 'place,cinema' },
  { id: 'airport', da: 'Lufthavn', en: 'Airport', de: 'Flughafen', imageSeed: 'place,airport' },
  { id: 'castle', da: 'Slot', en: 'Castle', de: 'Schloss', imageSeed: 'place,castle' },
  { id: 'supermarket', da: 'Supermarked', en: 'Supermarket', de: 'Supermarkt', imageSeed: 'place,supermarket' },
  { id: 'gym', da: 'Fitnesscenter', en: 'Gym', de: 'Fitnessstudio', imageSeed: 'place,gym' },
  { id: 'museum', da: 'Museum', en: 'Museum', de: 'Museum', imageSeed: 'place,museum' },
  { id: 'farm', da: 'Bondegård', en: 'Farm', de: 'Bauernhof', imageSeed: 'place,farm' },
  { id: 'hospital', da: 'Hospital', en: 'Hospital', de: 'Krankenhaus', imageSeed: 'place,hospital' },
  { id: 'school', da: 'Skole', en: 'School', de: 'Schule', imageSeed: 'place,school' },
  { id: 'university', da: 'Universitet', en: 'University', de: 'Universität', imageSeed: 'place,university' },
  { id: 'church', da: 'Kirke', en: 'Church', de: 'Kirche', imageSeed: 'place,church' },
  { id: 'mosque', da: 'Moske', en: 'Mosque', de: 'Moschee', imageSeed: 'place,mosque' },
  { id: 'temple', da: 'Tempel', en: 'Temple', de: 'Tempel', imageSeed: 'place,temple' },
  { id: 'stadium', da: 'Stadion', en: 'Stadium', de: 'Stadion', imageSeed: 'place,stadium' },
  { id: 'park', da: 'Park', en: 'Park', de: 'Park', imageSeed: 'place,park' },
  { id: 'playground', da: 'Legeplads', en: 'Playground', de: 'Spielplatz', imageSeed: 'place,playground' },
  { id: 'zoo', da: 'Zoo', en: 'Zoo', de: 'Zoo', imageSeed: 'place,zoo' },
  { id: 'aquarium', da: 'Akvarium', en: 'Aquarium', de: 'Aquarium', imageSeed: 'place,aquarium' },
  { id: 'planetarium', da: 'Planetarium', en: 'Planetarium', de: 'Planetarium', imageSeed: 'place,planetarium' },
  { id: 'observatory', da: 'Observatorium', en: 'Observatory', de: 'Observatorium', imageSeed: 'place,observatory' },
  { id: 'laboratory', da: 'Laboratorium', en: 'Laboratory', de: 'Labor', imageSeed: 'place,laboratory' },
  { id: 'factory', da: 'Fabrik', en: 'Factory', de: 'Fabrik', imageSeed: 'place,factory' },
  { id: 'warehouse', da: 'Lager', en: 'Warehouse', de: 'Lagerhaus', imageSeed: 'place,warehouse' },
  { id: 'office', da: 'Kontor', en: 'Office', de: 'Büro', imageSeed: 'place,office' },
  { id: 'shop', da: 'Butik', en: 'Shop', de: 'Laden', imageSeed: 'place,shop' },
  { id: 'mall', da: 'Indkøbscenter', en: 'Mall', de: 'Einkaufszentrum', imageSeed: 'place,mall' },
  { id: 'restaurant', da: 'Restaurant', en: 'Restaurant', de: 'Restaurant', imageSeed: 'place,restaurant' },
  { id: 'cafe', da: 'Cafe', en: 'Cafe', de: 'Café', imageSeed: 'place,cafe' },
  { id: 'bar', da: 'Bar', en: 'Bar', de: 'Bar', imageSeed: 'place,bar' },
  { id: 'club', da: 'Klub', en: 'Club', de: 'Club', imageSeed: 'place,club' },
  { id: 'theater', da: 'Teater', en: 'Theater', de: 'Theater', imageSeed: 'place,theater' },
  { id: 'opera', da: 'Opera', en: 'Opera', de: 'Oper', imageSeed: 'place,opera' },
  { id: 'concert_hall', da: 'Koncertsal', en: 'Concert Hall', de: 'Konzertsaal', imageSeed: 'place,concert' },
  { id: 'gallery', da: 'Galleri', en: 'Gallery', de: 'Galerie', imageSeed: 'place,gallery' },
  { id: 'studio', da: 'Studie', en: 'Studio', de: 'Studio', imageSeed: 'place,studio' },
  { id: 'workshop', da: 'Værksted', en: 'Workshop', de: 'Werkstatt', imageSeed: 'place,workshop' },
  { id: 'garage', da: 'Garage', en: 'Garage', de: 'Garage', imageSeed: 'place,garage' },
  { id: 'attic', da: 'Loft', en: 'Attic', de: 'Dachboden', imageSeed: 'place,attic' },
  { id: 'balcony', da: 'Altan', en: 'Balcony', de: 'Balkon', imageSeed: 'place,balcony' },
  { id: 'terrace', da: 'Terrasse', en: 'Terrace', de: 'Terrasse', imageSeed: 'place,terrace' },
  { id: 'roof', da: 'Tag', en: 'Roof', de: 'Dach', imageSeed: 'place,roof' },
  { id: 'island', da: 'Ø', en: 'Island', de: 'Insel', imageSeed: 'place,island' },
];

export const WHEN_ITEMS: MysteryItem[] = [
  { id: 'midnight', da: 'Midnat', en: 'Midnight', de: 'Mitternacht', imageSeed: 'time,midnight' },
  { id: 'morning', da: 'Morgen', en: 'Morning', de: 'Morgen', imageSeed: 'time,morning' },
  { id: 'dawn', da: 'Daggry', en: 'Dawn', de: 'Dämmerung', imageSeed: 'time,dawn' },
  { id: 'winter', da: 'Vinter', en: 'Winter', de: 'Winter', imageSeed: 'time,winter' },
  { id: 'christmas', da: 'Juleaften', en: 'Christmas Eve', de: 'Heiligabend', imageSeed: 'time,christmas' },
  { id: 'lunch_break', da: 'Spisepause', en: 'Lunch Break', de: 'Mittagspause', imageSeed: 'time,lunch' },
  { id: 'sunset', da: 'Solnedgang', en: 'Sunset', de: 'Sonnenuntergang', imageSeed: 'time,sunset' },
  { id: 'night', da: 'Nat', en: 'Night', de: 'Nacht', imageSeed: 'time,night' },
  { id: 'summer', da: 'Sommer', en: 'Summer', de: 'Sommer', imageSeed: 'time,summer' },
  { id: 'weekend', da: 'Weekend', en: 'Weekend', de: 'Wochenende', imageSeed: 'time,weekend' },
  { id: 'easter', da: 'Påske', en: 'Easter', de: 'Ostern', imageSeed: 'time,easter' },
  { id: 'halloween', da: 'Halloween', en: 'Halloween', de: 'Halloween', imageSeed: 'time,halloween' },
  { id: 'birthday', da: 'Fødselsdag', en: 'Birthday', de: 'Geburtstag', imageSeed: 'time,birthday' },
  { id: 'full_moon', da: 'Fuldmåne', en: 'Full Moon', de: 'Vollmond', imageSeed: 'time,moon' },
  { id: 'rush_hour', da: 'Myldretid', en: 'Rush Hour', de: 'Berufsverkehr', imageSeed: 'time,traffic' },
  { id: 'breakfast', da: 'Morgenmad', en: 'Breakfast', de: 'Frühstück', imageSeed: 'time,breakfast' },
  { id: 'dinner', da: 'Aftensmad', en: 'Dinner', de: 'Abendessen', imageSeed: 'time,dinner' },
  { id: 'tea_time', da: 'Tetid', en: 'Tea Time', de: 'Teezeit', imageSeed: 'time,tea' },
  { id: 'bedtime', da: 'Sengetid', en: 'Bedtime', de: 'Schlafenszeit', imageSeed: 'time,bedtime' },
  { id: 'nap_time', da: 'Lur', en: 'Nap Time', de: 'Mittagsschlaf', imageSeed: 'time,nap' },
  { id: 'playtime', da: 'Legetid', en: 'Playtime', de: 'Spielzeit', imageSeed: 'time,play' },
  { id: 'study_time', da: 'Studietid', en: 'Study Time', de: 'Lernzeit', imageSeed: 'time,study' },
  { id: 'work_time', da: 'Arbejdstid', en: 'Work Time', de: 'Arbeitszeit', imageSeed: 'time,work' },
  { id: 'vacation', da: 'Ferie', en: 'Vacation', de: 'Urlaub', imageSeed: 'time,vacation' },
  { id: 'holiday', da: 'Helligdag', en: 'Holiday', de: 'Feiertag', imageSeed: 'time,holiday' },
  { id: 'new_year', da: 'Nytår', en: 'New Year', de: 'Neujahr', imageSeed: 'time,newyear' },
  { id: 'carnival', da: 'Karneval', en: 'Carnival', de: 'Karneval', imageSeed: 'time,carnival' },
  { id: 'festival', da: 'Festival', en: 'Festival', de: 'Festival', imageSeed: 'time,festival' },
  { id: 'concert_time', da: 'Koncert', en: 'Concert', de: 'Konzert', imageSeed: 'time,concert' },
  { id: 'match_time', da: 'Kamp', en: 'Match', de: 'Spiel', imageSeed: 'time,match' },
  { id: 'race_time', da: 'Løb', en: 'Race', de: 'Rennen', imageSeed: 'time,race' },
  { id: 'exam_time', da: 'Eksamen', en: 'Exam', de: 'Prüfung', imageSeed: 'time,exam' },
  { id: 'graduation', da: 'Dimission', en: 'Graduation', de: 'Abschlussfeier', imageSeed: 'time,graduation' },
  { id: 'wedding', da: 'Bryllup', en: 'Wedding', de: 'Hochzeit', imageSeed: 'time,wedding' },
  { id: 'party_time', da: 'Fest', en: 'Party', de: 'Party', imageSeed: 'time,party' },
  { id: 'meeting_time', da: 'Møde', en: 'Meeting', de: 'Besprechung', imageSeed: 'time,meeting' },
  { id: 'appointment', da: 'Aftale', en: 'Appointment', de: 'Termin', imageSeed: 'time,appointment' },
  { id: 'interview', da: 'Interview', en: 'Interview', de: 'Interview', imageSeed: 'time,interview' },
  { id: 'presentation', da: 'Præsentation', en: 'Presentation', de: 'Präsentation', imageSeed: 'time,presentation' },
  { id: 'workshop_time', da: 'Workshop', en: 'Workshop', de: 'Workshop', imageSeed: 'time,workshop' },
  { id: 'seminar', da: 'Seminar', en: 'Seminar', de: 'Seminar', imageSeed: 'time,seminar' },
  { id: 'lecture', da: 'Forelæsning', en: 'Lecture', de: 'Vorlesung', imageSeed: 'time,lecture' },
  { id: 'class_time', da: 'Time', en: 'Class', de: 'Unterricht', imageSeed: 'time,class' },
  { id: 'break_time', da: 'Pause', en: 'Break', de: 'Pause', imageSeed: 'time,break' },
  { id: 'interval', da: 'Interval', en: 'Interval', de: 'Intervall', imageSeed: 'time,interval' },
  { id: 'season', da: 'Sæson', en: 'Season', de: 'Saison', imageSeed: 'time,season' },
  { id: 'spring', da: 'Forår', en: 'Spring', de: 'Frühling', imageSeed: 'time,spring' },
  { id: 'autumn', da: 'Efterår', en: 'Autumn', de: 'Herbst', imageSeed: 'time,autumn' },
  { id: 'decade', da: 'Årti', en: 'Decade', de: 'Jahrzehnt', imageSeed: 'time,decade' },
  { id: 'century', da: 'Århundrede', en: 'Century', de: 'Jahrhundert', imageSeed: 'time,century' },
];
